NEGATIVE_WITHDRAWAL = "Nide brain small"
WITHDRAWAL_TOO_LARGE = "Ni greedy. Ni ask for too much"

AMOUNT_QUERY = "How much? (in credits)"
INVALID_VALUE_ERROR_MESSAGE = "How much? (in credits)"
NO_MORE_ATTEMPTS_MESSAGE = "Ni greedy. Wait for next reset"

UNEXPECTED_ERROR_MESSAGE = "Unknown error occured."
NO_USERS_FOUND = "No users found"

STARTING_ATTEMPTS = 3
MEAN_DAILY_TOP_UP = 30

ADMIN_ID = 769354644

# /take flags
UNEXPECTED_ERROR = -1
USER_DUMB = 0
USER_GREEDY = 1
USER_SUCCESS = 2
success_threshold = 100

BAD = ["ni cai bad", "RAWR", "wochini", "???", "qiao ni"]

# Sticker IDs
# For /bad
CAT_WHACK_CAT = "CAACAgUAAxkBAAIH2Wj_Hnwwd9OTi0Kdy9r0IorEHhieAAIBBQAC3DYAAVR0AAFI7IaPNBI2BA"
BANG_TABLE = "CAACAgIAAxkBAAIH2mj_HpfXNsEkLwIiaeRDdAn81n8xAALTFgACyjcAAUnej6IEl_JRWzYE"
PANDEBUG_SNEEZE = "CAACAgEAAxkBAAIH3mj_Hu3pjkO5rsqK5Uimx1F02gJyAAMFAAI7W9FGoxtFCB38yFg2BA"
CAT_SHAKE_HEAD = "CAACAgUAAxkBAAIH32j_HwrnGyMuwmKJhjG93qOlSVWIAAIUBQAC5BPgV3UoKp0M1AWQNgQ"
PICHU_HIDDU = "CAACAgQAAxkBAAIH4Gj_H2VCrRGTbqHiFFiAz5aCBLR2AAJ7AQACb99yBYEqyybFb9LWNgQ"
PANDEBUG_LIFT_ROCKS = "CAACAgUAAxkBAAIH42j_INwizE38K9VSKQTI9zj21MYRAAJ0BQACqqU4VaM3BnWrqnSxNgQ"
PANDEBUG_RAWR = "CAACAgUAAxkBAAIH5Gj_IO_qH1Lig5nQQ9AxR-Y_qnyYAAKUBAAC96o5VQiOM-Qebmc6NgQ"
BAD_STICKERES = [CAT_WHACK_CAT, BANG_TABLE, PANDEBUG_SNEEZE, CAT_SHAKE_HEAD, PICHU_HIDDU, PANDEBUG_LIFT_ROCKS, PANDEBUG_RAWR]

# For congratulations
THUMBS_UP = "CAACAgQAAxkBAAIH22j_Hq1jBsitHzyJMPVhOisd4uNCAAIxAwACS2nuEPbkNZRztNZ2NgQ"
EXCITED_POP_UP = "CAACAgQAAxkBAAIH3Gj_HsrfTwqNgdFVawZrky7AZygpAALeAgACiAf-KPiLinG08neeNgQ"
HULA_HOOP = "CAACAgQAAxkBAAIH3Wj_Ht35SsmVn_aNz47TTlo-ida1AAKDCAACPMY4Uu2Ozii6ClMyNgQ"
CONGRATS = "CAACAgQAAxkBAAIH4Wj_H4iWOHSxiu3fTcgREmdgmwchAAMDAAKIB_4oWzBhvNXRfmY2BA"
PANDEBUG_HAPPY_SPIN = "CAACAgEAAxkBAAIH4mj_H6RFbc-FAp2zz-lJXC4cI9OaAAIhBAACH0rQRtyuQHsGc2KBNgQ"
COGRATULATIONS_STICKERS = [THUMBS_UP, EXCITED_POP_UP, HULA_HOOP, CONGRATS, PANDEBUG_HAPPY_SPIN]

# Confusions
QUESTION_MARKS = "CAACAgQAAxkBAAIIEmj_Jhf5kXOPqyXvrIylj_y3FH3WAAIsAwACS2nuEJeEMD8xy6GZNgQ"
CONFUSION_STICKERS = [QUESTION_MARKS]

# Others
HAACHAMA_PANIC = "CAACAgIAAxkBAAIH1mj_HM87JsFF33aUI9oZPxOGDdqZAAJrAQACoykFCDj4-TIWhFrLNgQ"

