NEGATIVE_WITHDRAWAL = "Nide brain small"
WITHDRAWAL_TOO_LARGE = "Ni greedy. Ni ask for too much"

AMOUNT_QUERY = "How much? (in credits)"
INVALID_VALUE_ERROR_MESSAGE = "Enter integer value"
NO_MORE_ATTEMPTS_MESSAGE = "Ni greedy. Wait for next reset"
USER_GREEDY_MESSAGE = "Ni greedy. Ni ask for too much"

UNEXPECTED_ERROR_MESSAGE = "Unknown error occured."
NO_USERS_FOUND = "No users found"

STARTING_ATTEMPTS = 3
MEAN_DAILY_TOP_UP = 30
MAX_DAILY_TOP_UP = 300

DEFAULT_STICKER_COMBO = 6

ADMIN_ID = 769354644

# /take flags
UNEXPECTED_ERROR = -1
USER_DUMB = 0
USER_GREEDY = 1
USER_SUCCESS = 2
success_threshold = 100

BAD = ["ni cai bad", "RAWR", "wochini", "???", "qiao ni"]

# Sticker IDs
# For /bad
PANDEBUG_SNEEZE = "CAACAgEAAxkBAAIH3mj_Hu3pjkO5rsqK5Uimx1F02gJyAAMFAAI7W9FGoxtFCB38yFg2BA"
CAT_SHAKE_HEAD = "CAACAgUAAxkBAAIH32j_HwrnGyMuwmKJhjG93qOlSVWIAAIUBQAC5BPgV3UoKp0M1AWQNgQ"
PICHU_HIDDU = "CAACAgQAAxkBAAIH4Gj_H2VCrRGTbqHiFFiAz5aCBLR2AAJ7AQACb99yBYEqyybFb9LWNgQ"
PANDEBUG_LIFT_ROCKS = "CAACAgUAAxkBAAIH42j_INwizE38K9VSKQTI9zj21MYRAAJ0BQACqqU4VaM3BnWrqnSxNgQ"
CAT_SAD = "CAACAgUAAxkBAAII72j_ZzB7SWjmu5kGDjL1aHsPGXalAALeAwACxaPRV8uIs8aUoMFPNgQ"
BAD_STICKERS = [PANDEBUG_SNEEZE, CAT_SHAKE_HEAD, PICHU_HIDDU, PANDEBUG_LIFT_ROCKS, CAT_SAD]

# For good
PANDEBUG_HAPPY_SPIN = "CAACAgEAAxkBAAIH4mj_H6RFbc-FAp2zz-lJXC4cI9OaAAIhBAACH0rQRtyuQHsGc2KBNgQ"
PANDEBUG_DANCE = "CAACAgUAAxkBAAII5mj_Y97rkYnYjNHslGEpqpJxp_qIAAImBQACTsM4VTJesR-ZiXUdNgQ"
PANDEBUG_CLAP = "CAACAgUAAxkBAAIH1Wj_HMjguI2_XsA6f3Zb2cZiJ3XYAAIxBQACgxI5VSgnUhiJXhwNNgQ"
BAO_EXCITED_POP_UP = "CAACAgQAAxkBAAIH3Gj_HsrfTwqNgdFVawZrky7AZygpAALeAgACiAf-KPiLinG08neeNgQ"
CAT_HAPPY_BITE_PAW = "CAACAgQAAx0CTK03NgABAnPTaP-cCjJp5l1fPNACjNHS4TwgUa4AAl0TAAIuAmlRMo0C84S34dU2BA"
GOOD_STICKERS = [PANDEBUG_HAPPY_SPIN, PANDEBUG_DANCE, PANDEBUG_CLAP, BAO_EXCITED_POP_UP, CAT_HAPPY_BITE_PAW]

# For congratulations
BAO_CONGRATS = "CAACAgQAAxkBAAIH4Wj_H4iWOHSxiu3fTcgREmdgmwchAAMDAAKIB_4oWzBhvNXRfmY2BA"
COGRATULATIONS_STICKERS = [BAO_CONGRATS]

# Confusions
QOOBEE_QUESTION_MARKS = "CAACAgQAAxkBAAIIEmj_Jhf5kXOPqyXvrIylj_y3FH3WAAIsAwACS2nuEJeEMD8xy6GZNgQ"
CONFUSION_STICKERS = [QOOBEE_QUESTION_MARKS]

# Dataa/huaidan
CAT_WHACK_CAT = "CAACAgUAAxkBAAIH2Wj_Hnwwd9OTi0Kdy9r0IorEHhieAAIBBQAC3DYAAVR0AAFI7IaPNBI2BA"
WHACK_STICKERS = [CAT_WHACK_CAT]

# Sad
CAT_GET_PET = "CAACAgUAAxkBAAII8Wj_Z1R_2fiW4ILmF46TxXvp1rH7AAIVBgACi8DJVQ6G6anLAAFckTYE"
BAO_SAD = "CAACAgQAAxkBAAII7Gj_ZUiqUle4Q9Oj2pTZ8vIKUtfNAAIHAwACiAf-KBB3Nz_kf3_bNgQ"
SAD_STICKERS = [CAT_GET_PET, BAO_SAD]

# Ni have no proof
PANDEBUG_MOCK = "CAACAgEAAxkBAAII9Wj_aXdWl0Jnv1-vidNhvj34h0lUAAITCAACPvHQRYv3-HfFlaltNgQ"
PROOF_STICKERS = [PANDEBUG_MOCK]

# Peppercorn/hangyodon
PANDEBUG_JAIL = "CAACAgEAAxkBAAII7mj_ZxGpu0bRLdJBUIGt7IfsJub6AAL9AgACao3YRQfTqg_ppYt_NgQ"
PANDEBUG_RAWR = "CAACAgUAAxkBAAIH5Gj_IO_qH1Lig5nQQ9AxR-Y_qnyYAAKUBAAC96o5VQiOM-Qebmc6NgQ"
PEPPERCORN_STICKERS = [PANDEBUG_JAIL, PANDEBUG_RAWR]

# Chini
PANDEBUG_STARU_CHEESE = "CAACAgEAAxkBAAII42j_Y38TqiOmE8zLtsL7zg94IDzQAAIbBAACHCzRRiw3NkjwHHI_NgQ"
CHINI_STICKERS = [PANDEBUG_STARU_CHEESE]

# Cole joke/hi bored
BAO_LAUGH = "CAACAgQAAxkBAAII6mj_ZNcfUDF08pPKWHjU11S39_9nAALgAgACiAf-KN48pQQsiYfkNgQ"
QOOBEE_LAUGH = "CAACAgQAAxkBAAII7Wj_ZWb9DhuOA-W8j_6_AgxEG9SgAAKDDAACS2nuENrvZ0DDAAHSRjYE"
LAUGH_STICKERS = [BAO_LAUGH, QOOBEE_LAUGH]

# Shuijiao
CHICK_TUCKU = "CAACAgIAAxkBAAII9Gj_Z66M68f_0wIqZFfxCcdFYhglAAKFGAACIuUBSUhYk2dgX4qxNgQ"
CHICK_SLEEPU = "CAACAgIAAxkBAAIJe2j_exMgr56w9CL6Pg2Bee-D9XnVAALmEgAC00v4SHG2Wqr8ldwSNgQ"
SLEEP_STICKERS = [CHICK_TUCKU, CHICK_SLEEPU]

# Pointu
BAO_POINTU = "CAACAgQAAxkBAAII62j_ZOuto8-oX6BmUPBo9kGnx9voAALpAgACiAf-KLDy397Umm91NgQ"
POINTU_STICKERS = [BAO_POINTU]

# Remember
QOOBEE_SCRIBBU = "CAACAgQAAxkBAAII6Wj_ZGCcd1HZM_mo6G-TtYYWwatTAAIwAwACS2nuEOAcesYSIjGdNgQ"
REMEMBER_STICKERS = [QOOBEE_SCRIBBU]

# Lookie
PANDEBUG_STARU_PIECE = "CAACAgUAAxkBAAIJgGj_fLS_RbCw2wvNGTEfv-GVa_p7AAK3BgAClMo4VSCfmP_coq-SNgQ"
PANDEBUG_STARU = "CAACAgEAAxkBAAII4Wj_Y1LPW1rK49jbEzeo9OnaMlsyAAI3BAACiu3QRicXW1_gEwS4NgQ"
PANDEBUG_SIT_TABLE = "CAACAgUAAxkBAAIH52j_IUcnVpugQCkCClngvxPnPsEaAAICBQACWVo5VaoEnQK633GUNgQ"
PANDEBUG_POPCORN = "CAACAgUAAxkBAAII5Wj_Y8p8sHrovnynG4e6l9SUIsX1AALKAwACib04VWHZ7l7DuB71NgQ"
QOOBEE_LOOKIE = "CAACAgQAAxkBAAII6Gj_ZEWxKEvNoKpv43Myc1zVryDBAAItAwACS2nuEPffUiaMlnZWNgQ"
CAT_LOOKIE = "CAACAgIAAxkBAAII82j_Z4Y8XdHaM6PH4gGttPpr7ciRAAIeGQACmLlBSI6DgjvOEkfNNgQ"
PANDEBUG_PUFF_CHEEKS = "CAACAgEAAxkBAAII4mj_Y13o317-X_Zr_lapEotOeeNxAAJ-BQACy2fZRm6deObeNcEWNgQ"
LOOKIE_STICKERS = [PANDEBUG_STARU_PIECE, PANDEBUG_STARU, PANDEBUG_SIT_TABLE, PANDEBUG_POPCORN, QOOBEE_LOOKIE,
                   CAT_LOOKIE, PANDEBUG_PUFF_CHEEKS]

# Angry stickers
CHICK_BANG_TABLE = "CAACAgIAAxkBAAIH2mj_HpfXNsEkLwIiaeRDdAn81n8xAALTFgACyjcAAUnej6IEl_JRWzYE"
DOG_ANGRY = "CAACAgUAAxkBAAIKxmkAAaESiNDFiG4VY_Skg0jw8ilcJQAC_QIAAn9YiFcI-7xZ3fLLdTYE"
ANGRY_STICKERS = [CHICK_BANG_TABLE, DOG_ANGRY]

# Woyao stickers
WOYAO_STICKERS = [PANDEBUG_SIT_TABLE, PANDEBUG_STARU]

# Okie stickers
QOOBEE_THUMBS_UP = "CAACAgQAAxkBAAIH22j_Hq1jBsitHzyJMPVhOisd4uNCAAIxAwACS2nuEPbkNZRztNZ2NgQ"
OKIE_STIKCERS = [QOOBEE_THUMBS_UP]

# Others
HAACHAMA_PANIC = "CAACAgIAAxkBAAIH1mj_HM87JsFF33aUI9oZPxOGDdqZAAJrAQACoykFCDj4-TIWhFrLNgQ"
PANDEBUG_ROLL = "CAACAgUAAxkBAAII52j_Y_424igQ8PYvxht9FSd8PvRzAAKPBAAC4yw4VVfnNK4kC62gNgQ"
PANDEBUG_SKIP_ROPE = "CAACAgUAAxkBAAIIw2j_MUMdOePjlXeJAfn1az-NXknOAALUBQACJ044VUsbdmY_NoMNNgQ"
CAT_GET_POKED = "CAACAgUAAxkBAAII8Gj_Z0CvzvtuNPq5i1TVxC3uKAAB-AACBQUAAomC4Vd3XJ1TozXlFzYE"
CAT_SNEAKU = "CAACAgUAAxkBAAII8mj_Z3Bkc6I4LTxPKPyeaBL1HAYnAAI9BQACLSHJVSOfVOaN8LlWNgQ"
HULA_HOOP = "CAACAgQAAxkBAAIH3Wj_Ht35SsmVn_aNz47TTlo-ida1AAKDCAACPMY4Uu2Ozii6ClMyNgQ"